import Head from 'next/head'
import { useState } from "react";

export default function Show({show}) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Name: </h1><span>{show.name}</span>
                <h1>Overview: </h1><span>{show.overview}</span>
                <h1>Seasons: </h1>
                {show.seasons.map((s,i) => 
                    <>
                        <span>{s.name}</span>
                        {(i < show.seasons.length - 1) &&
                            <span>, </span>
                        }
                    </>
                )}
            </main>

        </div>
    )
}

export async function getServerSideProps({params}) {
    const show = await fetchShow(params.id);
    return {props: {show}};
}

async function fetchShow(id){
    return await fetch(`https://api.themoviedb.org/3/tv/${id}?&api_key=753c37ef2f0908507dca0d4f9299faa0`).then(res => res.json());
}
